image: gitpod/workspace-java-17

tasks:
- init: mvn package -DskipTests
  command: java -jar target/*.jar

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-java-dependency
    - vscjava.vscode-spring-boot-dashboard
    - redhat.java
    - pivotal.vscode-boot-dev-pack
    - pivotal.vscode-spring-boot
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-maven
    - vscjava.vscode-java-pack
