image: gitpod/workspace-java-17

tasks:
- init: mvn package -DskipTests

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
    - pivotal.vscode-boot-dev-pack